version: '3'

services:
  app:
    image: nginx:latest
    container_name: my_app
    ports:
      - "80:80"
    environment:
      DB_PASSWORD: qwerty123
    volumes:
      - .:/app
    networks:
      - public_network

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: qwerty123
    networks:
      - public_network

networks:
  public_network:
    driver: bridge
