version: '3.8'

services:
  app:
    image: nginx:1.21-alpine
    container_name: my_app
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - app_data:/app
    networks:
      - private_network

  db:
    image: postgres:13
    env_file:
      - .env
    networks:
      - private_network

volumes:
  app_data:

networks:
  private_network:
    driver: bridge
