FROM ubuntu:latest

RUN apt-get update -y
RUN apt-get install -y python3 python3-pip
RUN python3 -m pip install --break-system-packages flask

COPY . /app
WORKDIR /app

RUN useradd -m myuser
USER myuser

EXPOSE 80

CMD ["python3", "app.py"]

