FROM python:3.9-slim

WORKDIR /app

# Копирование файла зависимостей и установка
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копирование остального кода
COPY . .

# Создание и смена пользователя
RUN groupadd -r myuser && useradd -r -g myuser myuser
USER myuser

EXPOSE 80

CMD ["python3", "app.py"]
